# Site
title:              Madhukhali Pilot High School
bio:                'Madhukhali Pilot High School is an academic institute located at Madhukhali Madhukhali Faridpur. Its institute code (EIIN) is 108814. It was established on 01 January, 1947. Its co-education type is Combined. The institute has following 3 disciplines : Business Studies, Science, Humanities. Average exam passing rate of the institute is : JSC/Equivalent: 86.38%, SSC/Equivalent: 80.83%, Its MPO number is 3208061301. It has 2 shift. Its management is Managing. [ This unofficial demo website is  created by Sohel Khan, ex-student of this institute.]'
description:        "Madhukhali Pilot High School is an academic institute located at Madhukhali Madhukhali Faridpur. Its institute code (EIIN) is 108814. It was established on 01 January, 1947. Its co-education type is Combined. The institute has following 3 disciplines : Business Studies, Science, Humanities. Average exam passing rate of the institute is : JSC/Equivalent: 86.38%, SSC/Equivalent: 80.83%, Its MPO number is 3208061301. It has 2 shift. Its management is Managing. [ This unofficial demo website is  created by Sohel Khan, ex-student of this institute.]"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/mphs.jpg'
background:         'assets/img/mphs2.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_UK
url:                https://mphs-edu.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   mphs

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:       'UA-193152863-1'
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:              @gmail.com
twitter:            mphs_edu
facebook:           mphs.edu
#github-url:         mphs-edu
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          mphs_edu
#lastfm:            username
#tumblr:            username
#medium:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
youtube:           mphs.edu
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#orcid:             username
#ads:               username
#figshare:          username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
